[project]
name = "Livt.IO"
version = "1.2.0"
path = "src"
outdir = "out"

[tests]
path = "tests"
components = [
    "RamTest",
    "DistributedRamTest",
    "UartReceiverTest",
    "UartTransmitterTest",
    "UartBaseTest",
    "BufferedUartTest",
    "UartTest",
    "LoopbackUartTest",
    "RtsCtsBufferedUartTest",
    "RtsCtsUartTest",
    "I2COpenDrainPinsTest",
    "I2CBusCombinerTest",
    "I2CMasterTest",
    "I2CSlaveTest",
    "I2CRegisterSlaveTest",
    "I2CIntegrationTest",
    "I2CReadIntegrationTest",
    "I2CRegisterIntegrationTest",
    "SPIMasterTest",
    "SPIMasterSlowContextTest"
]

[build.debug]
warnings = ["all"]

[build.release]
warnings = ["all"]
