[project]
name = "Livt.IO"
version = "1.2.0-dev"
path = "src"
outdir = "out"

[tests]
path = "tests"
components = [
    "GenericRamTest",
    "RamBackendTest",
    "SynchronousRamTest",
    "RamTest",
    "WideRamTest",
    "AsynchronousRamTest",
    "AsynchronousDistributedRamTest",
    "UartReceiverTest",
    "UartBaudConfigurationTest",
    "UartFrameConfigurationTest",
    "UartTransmitterTest",
    "UartTest",
    "BufferedUartPermissionTest",
    "UartCapacityTest",
    "ConcurrentUartTest",
    "BufferedUartTest",
    "BufferedUartApiTest",
    "LoopbackUartTest",
    "RtsCtsBufferedUartTest",
    "RtsCtsBufferedUartSmokeTest",
    "UartSynthesisConfigurationTest",
    "I2COpenDrainPinsTest",
    "I2CBusCombinerTest",
    "I2CMasterTest",
    "I2CSlaveTest",
    "I2CRegisterSlaveTest",
    "I2CIntegrationTest",
    "I2CReadIntegrationTest",
    "I2CRegisterIntegrationTest",
    "SPIMasterTest",
    "SPIMasterSlowContextTest"
]

[build.debug]
warnings = ["all"]

[build.release]
warnings = ["all"]

[dependencies]
Livt.Collections = "1.1.0-dev"
